#!/usr/bin/env python3

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "pypkg"))

from action_logging import log_action_failure
from hermes_user_domain import list_domain_users


def main():
	request = json.load(sys.stdin)
	json.dump({"users": list_domain_users(request["domain"])}, fp=sys.stdout)


if __name__ == "__main__":
	try:
		main()
	except Exception as error:
		log_action_failure("list-domain-users/10read", error)
		raise