name: "Publish images"

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  actions: read
  contents: write
  security-events: write

jobs:
  publish-images:
    if: github.run_number > 1
    uses: ./.github/workflows/build-images.yml
    with:
      imagetag: ${{ github.event.release.tag_name || github.ref_name }}
  module:
    needs: publish-images
    uses: NethServer/ns8-github-actions/.github/workflows/module-info.yml@v1
  trivy:
    needs: module

    if: ${{ needs.module.outputs.release == 'stable' || needs.module.outputs.release == 'latest' || github.event_name == 'workflow_dispatch' }}
    uses: NethServer/ns8-github-actions/.github/workflows/scan-with-trivy.yml@v1
    with:
      images: ${{ needs.module.outputs.images }}
